//! Embeds the built UI into the binary.
//!
//! `dist/` is committed (ADR-0009), so this adds no build step of its own: it walks the
//! directory and writes a lookup table. What it does add is a rebuild trigger, because
//! Cargo would otherwise not notice that a file under `dist/` changed.
//!
//! A missing or empty `dist/` is not a build failure. It would break `cargo run`, which
//! is the one promise ADR-0009 exists to keep, so instead it embeds a page that says what
//! to run. Failing loudly at compile time is right for a broken dependency; a UI that was
//! simply never built is not one.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let dist = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("dist");
    println!("cargo:rerun-if-changed=build.rs");

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    match std::fs::read_dir(&dist) {
        Ok(entries) => {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_file() {
                    files.push((format!("/{}", file_name(&path)), path));
                } else if path.is_dir() {
                    // The directory's own name is part of the URL — Vite emits
                    // `dist/assets/app.js` and asks for `/assets/app.js`.
                    let name = file_name(&path);
                    collect(&path, &format!("/{name}"), &mut files);
                }
            }
        }
        Err(_) => println!("cargo:warning=dist/ is missing — embedding the 'not built' page"),
    }
    files.sort();

    let mut body = String::from(
        "// Generated by build.rs from `dist/`. Do not edit: run `npm --prefix ui run\n\
         // build` and commit the result.\n\n\
         pub static ASSETS: &[(&str, &str)] = &[\n",
    );

    if files.is_empty() {
        // Absolute, because `include_str!` resolves relative to *this* generated file,
        // which lives in OUT_DIR — not relative to `src/`, and not relative to the crate
        // root. A bare "unbuilt.html" compiled fine on macOS only because a stale OUT_DIR
        // still held a copy; on a clean checkout it is a hard error, which is the one
        // situation the fallback exists for.
        let fallback = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("src")
            .join("unbuilt.html");
        let _ = write!(
            body,
            "    (\"/\", include_str!({:?})),",
            fallback.display().to_string()
        );
    } else {
        for (url, path) in &files {
            println!("cargo:rerun-if-changed={}", path.display());
            let _ = writeln!(
                body,
                "    ({:?}, include_str!({:?})),",
                url,
                path.display().to_string()
            );
        }
    }

    let _ = writeln!(body, "];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    std::fs::write(out.join("assets.rs"), body).expect("could not write the asset table");
}

/// Walk a subdirectory of `dist/`, giving every file its URL path.
///
/// `prefix` is the file's own directory with a leading slash and no trailing one, so
/// `/assets` for `dist/assets`. Joining on `/` rather than interpolating keeps the
/// double slash that turns `/assets/app.js` into `//assets/app.js` out of the table.
fn collect(dir: &Path, prefix: &str, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let name = file_name(&path);
        if path.is_dir() {
            collect(&path, &format!("{prefix}/{name}"), out);
        } else if path.is_file() {
            out.push((format!("{prefix}/{name}"), path));
        }
    }
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .unwrap_or_default()
        .to_string_lossy()
        .into_owned()
}
